### ISSUE TITLE
Support for SVG and EOT formats

### ISSUE THREAD

**Issue by firegurafiku** [battlesnake/gulp-google-webfonts#28]
Hi, guys.

Shouldn't the plugin support for EOT and SVG formats as well? I'm very occasionally do something web-related, so I'm not sure if these formats are still relevant to the world, but Google WebFonts seems to provide source files for them as well.

For example, if I navigate to https://fonts.googleapis.com/css?family=PT+Serif with custom User-Agent, I get the following results:

```css
/** User-Agent: Mozilla/5.0 (iPhone; U; CPU iPhone OS 3_0 like Mac OS X; en-us)
    AppleWebKit/528.18 (KHTML, like Gecko) Version/4.0 Mobile/7A341 Safari/528.16 */
@font-face {
  font-family: 'PT Serif';
  font-style: normal;
  font-weight: 400;
  src: local('PT Serif'), local('PTSerif-Regular'), url(...) format('svg');
}

/* User-Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1) */
@font-face {
  font-family: 'PT Serif';
  font-style: normal;
  font-weight: 400;
  src: url(...);
}
```

I've cut original long URLs from the above output to get rid of horizontal scrolling, but here they are:
* [SVG font](https://fonts.gstatic.com/l/font?kit=zSUbs06MuKAdU7m-SV4ok_esZW2xOQ-xsNqO47m55DA&skey=e37119e9cd703ddf&v=v8#PTSerif)
* [EOT font](https://fonts.gstatic.com/s/ptserif/v8/0Om6Iw1e323HjeZHy8W4rfesZW2xOQ-xsNqO47m55DA.eot)

In #18 @michaelmior [wrote][comment] that it would be relatively easy to incorporate support for other formats given that their User-Agents are known.

[comment]: https://github.com/battlesnake/gulp-google-webfonts/issues/18#issuecomment-233461676
