### ISSUE TITLE
Support for generate css with woff and woff2 fonts

### ISSUE THREAD

**Issue by JosefJezek** [battlesnake/gulp-google-webfonts#32]
```css
@font-face {
      font-family: 'Roboto';
      font-style: normal;
      font-weight: 400;
      /* Use local copy of font, if the user does not have that font installed (two different names are tried),
         then the downloadable font is used instead. */
      src: local('Roboto'), local('Roboto-Regular'),
           url(Roboto-normal-400.woff2) format('woff2'),
           url(Roboto-normal-400.woff) format('woff');
    }
```

Safari support woff2 http://caniuse.com/#search=woff2
