### ISSUE TITLE
Option for WOFF2

### ISSUE THREAD

**Issue by JosefJezek** [battlesnake/gulp-google-webfonts#5]
Please add Option for WOFF2.

**Comment by battlesnake** [comment]
Neither IE nor Safari support it, so it's not particularly important for me.  Feel free to add it yourself and send a pull-request.

**Comment by JosefJezek** [comment]
IE and Safari are dead ;-)

# Embed WOFF2 in CSS (with WOFF fallback)

```
@font-face {
    font-family: MyFont;
    src:
        url('myfont.woff2') format('woff2'),
        url('myfont.woff') format('woff');
}
```

https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

**Comment by JosefJezek** [comment]
Please, I am working on https://github.com/StartPolymer/polymer-starter-kit-plus

I used your plugin https://github.com/StartPolymer/polymer-starter-kit-plus/blob/master/fonts.list

**Comment by JosefJezek** [comment]
Please open

**Comment by battlesnake** [comment]
@JosefJezek If it's important to you, send a pull request.  I'm not wasting time implementing a feature that two major browsers don't support.

**Comment by michaelmior** [comment]
@JosefJezek There is now a `format` option which accepts a value of `woff2` that will do this.

**Comment by JosefJezek** [comment]
@battlesnake @michaelmior Could you add support for generate css with woff and woff2 fonts?

```css
  @font-face {
      font-family: 'Roboto';
      font-style: normal;
      font-weight: 400;
      /* Use local copy of font, if the user does not have that font installed (two different names are tried),
         then the downloadable font is used instead. */
      src: local('Roboto'), local('Roboto-Regular'),
           url(fonts/roboto/v15/latin-ext/roboto-400-fIKu7GwZTy_12XzG_jt8eA.woff2) format('woff2'),
           url(fonts/roboto/v15/latin-ext/roboto-400-Xyjz-jNkfiYuJf8UC3Lizw.woff) format('woff');
    }
```
